// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.iot.deviceupdate.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Failure conditions to initiate rollback policy.
 */
@Immutable
public final class CloudInitiatedRollbackPolicyFailure {
    /*
     * Percentage of devices that failed.
     */
    @Generated
    @JsonProperty(value = "devicesFailedPercentage")
    private int devicesFailedPercentage;

    /*
     * Number of devices that failed.
     */
    @Generated
    @JsonProperty(value = "devicesFailedCount")
    private int devicesFailedCount;

    /**
     * Creates an instance of CloudInitiatedRollbackPolicyFailure class.
     * 
     * @param devicesFailedPercentage the devicesFailedPercentage value to set.
     * @param devicesFailedCount the devicesFailedCount value to set.
     */
    @Generated
    @JsonCreator
    public CloudInitiatedRollbackPolicyFailure(
        @JsonProperty(value = "devicesFailedPercentage") int devicesFailedPercentage,
        @JsonProperty(value = "devicesFailedCount") int devicesFailedCount) {
        this.devicesFailedPercentage = devicesFailedPercentage;
        this.devicesFailedCount = devicesFailedCount;
    }

    /**
     * Get the devicesFailedPercentage property: Percentage of devices that failed.
     * 
     * @return the devicesFailedPercentage value.
     */
    @Generated
    public int getDevicesFailedPercentage() {
        return this.devicesFailedPercentage;
    }

    /**
     * Get the devicesFailedCount property: Number of devices that failed.
     * 
     * @return the devicesFailedCount value.
     */
    @Generated
    public int getDevicesFailedCount() {
        return this.devicesFailedCount;
    }
}
