// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.iot.deviceupdate.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Rollback policy for deployment.
 */
@Immutable
public final class CloudInitiatedRollbackPolicy {
    /*
     * Update to rollback to.
     */
    @Generated
    @JsonProperty(value = "update")
    private UpdateInfo update;

    /*
     * Failure conditions to initiate rollback policy.
     */
    @Generated
    @JsonProperty(value = "failure")
    private CloudInitiatedRollbackPolicyFailure failure;

    /**
     * Creates an instance of CloudInitiatedRollbackPolicy class.
     * 
     * @param update the update value to set.
     * @param failure the failure value to set.
     */
    @Generated
    @JsonCreator
    public CloudInitiatedRollbackPolicy(@JsonProperty(value = "update") UpdateInfo update,
        @JsonProperty(value = "failure") CloudInitiatedRollbackPolicyFailure failure) {
        this.update = update;
        this.failure = failure;
    }

    /**
     * Get the update property: Update to rollback to.
     * 
     * @return the update value.
     */
    @Generated
    public UpdateInfo getUpdate() {
        return this.update;
    }

    /**
     * Get the failure property: Failure conditions to initiate rollback policy.
     * 
     * @return the failure value.
     */
    @Generated
    public CloudInitiatedRollbackPolicyFailure getFailure() {
        return this.failure;
    }
}
