// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.iot.deviceupdate.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The Device Update agent contract model.
 */
@Immutable
public final class ContractModel {
    /*
     * The Device Update agent contract model Id of the device class. This is also
     * used to calculate the device class Id.
     */
    @Generated
    @JsonProperty(value = "id")
    private String id;

    /*
     * The Device Update agent contract model name of the device class. Intended to be
     * a more readable form of the contract model Id.
     */
    @Generated
    @JsonProperty(value = "name")
    private String name;

    /**
     * Creates an instance of ContractModel class.
     * 
     * @param id the id value to set.
     * @param name the name value to set.
     */
    @Generated
    @JsonCreator
    private ContractModel(@JsonProperty(value = "id") String id, @JsonProperty(value = "name") String name) {
        this.id = id;
        this.name = name;
    }

    /**
     * Get the id property: The Device Update agent contract model Id of the device class. This is also
     * used to calculate the device class Id.
     * 
     * @return the id value.
     */
    @Generated
    public String getId() {
        return this.id;
    }

    /**
     * Get the name property: The Device Update agent contract model name of the device class. Intended to be
     * a more readable form of the contract model Id.
     * 
     * @return the name value.
     */
    @Generated
    public String getName() {
        return this.name;
    }
}
