// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.iot.deviceupdate.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Deployment device status.
 */
@Immutable
public final class DeploymentDeviceState {
    /*
     * Device identity.
     */
    @Generated
    @JsonProperty(value = "deviceId", access = JsonProperty.Access.WRITE_ONLY)
    private String deviceId;

    /*
     * Device module identity.
     */
    @Generated
    @JsonProperty(value = "moduleId")
    private String moduleId;

    /*
     * The number of times this deployment has been retried on this device.
     */
    @Generated
    @JsonProperty(value = "retryCount")
    private int retryCount;

    /*
     * Boolean flag indicating whether this device is in a newer deployment and can no
     * longer retry this deployment.
     */
    @Generated
    @JsonProperty(value = "movedOnToNewDeployment")
    private boolean movedOnToNewDeployment;

    /*
     * Deployment device state.
     */
    @Generated
    @JsonProperty(value = "deviceState")
    private DeviceDeploymentState deviceState;

    /**
     * Creates an instance of DeploymentDeviceState class.
     * 
     * @param retryCount the retryCount value to set.
     * @param movedOnToNewDeployment the movedOnToNewDeployment value to set.
     * @param deviceState the deviceState value to set.
     */
    @Generated
    @JsonCreator
    private DeploymentDeviceState(@JsonProperty(value = "retryCount") int retryCount,
        @JsonProperty(value = "movedOnToNewDeployment") boolean movedOnToNewDeployment,
        @JsonProperty(value = "deviceState") DeviceDeploymentState deviceState) {
        this.retryCount = retryCount;
        this.movedOnToNewDeployment = movedOnToNewDeployment;
        this.deviceState = deviceState;
    }

    /**
     * Get the deviceId property: Device identity.
     * 
     * @return the deviceId value.
     */
    @Generated
    public String getDeviceId() {
        return this.deviceId;
    }

    /**
     * Get the moduleId property: Device module identity.
     * 
     * @return the moduleId value.
     */
    @Generated
    public String getModuleId() {
        return this.moduleId;
    }

    /**
     * Get the retryCount property: The number of times this deployment has been retried on this device.
     * 
     * @return the retryCount value.
     */
    @Generated
    public int getRetryCount() {
        return this.retryCount;
    }

    /**
     * Get the movedOnToNewDeployment property: Boolean flag indicating whether this device is in a newer deployment
     * and can no
     * longer retry this deployment.
     * 
     * @return the movedOnToNewDeployment value.
     */
    @Generated
    public boolean isMovedOnToNewDeployment() {
        return this.movedOnToNewDeployment;
    }

    /**
     * Get the deviceState property: Deployment device state.
     * 
     * @return the deviceState value.
     */
    @Generated
    public DeviceDeploymentState getDeviceState() {
        return this.deviceState;
    }
}
