// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.iot.deviceupdate.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.annotation.Generated;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;
import java.util.List;

/**
 * Deployment metadata.
 */
@Fluent
public final class Deployment {
    /*
     * The caller-provided deployment identifier. This cannot be longer than 73
     * characters, must be all lower-case, and cannot contain '&', '^', '[', ']', '{',
     * '}', '|', '<', '>', forward slash, backslash, or double quote. The Updates view
     * in the Azure Portal IoT Hub resource generates a GUID for deploymentId when you
     * create a deployment.
     */
    @Generated
    @JsonProperty(value = "deploymentId", access = JsonProperty.Access.WRITE_ONLY)
    private String deploymentId;

    /*
     * The deployment start datetime.
     */
    @Generated
    @JsonProperty(value = "startDateTime")
    private OffsetDateTime startDateTime;

    /*
     * Update information for the update in the deployment.
     */
    @Generated
    @JsonProperty(value = "update")
    private UpdateInfo update;

    /*
     * The group identity for the devices the deployment is intended to update.
     */
    @Generated
    @JsonProperty(value = "groupId")
    private String groupId;

    /*
     * The device class subgroups the deployment is compatible with and subgroup
     * deployments have been created for. This is not provided by the caller during
     * CreateOrUpdateDeployment but is automatically determined by Device Update
     */
    @Generated
    @JsonProperty(value = "deviceClassSubgroups", access = JsonProperty.Access.WRITE_ONLY)
    private List<String> deviceClassSubgroups;

    /*
     * Boolean flag indicating whether the deployment was canceled.
     */
    @Generated
    @JsonProperty(value = "isCanceled", access = JsonProperty.Access.WRITE_ONLY)
    private Boolean isCanceled;

    /*
     * Boolean flag indicating whether the deployment has been retried.
     */
    @Generated
    @JsonProperty(value = "isRetried", access = JsonProperty.Access.WRITE_ONLY)
    private Boolean isRetried;

    /*
     * The rollback policy for the deployment.
     */
    @Generated
    @JsonProperty(value = "rollbackPolicy")
    private CloudInitiatedRollbackPolicy rollbackPolicy;

    /*
     * Boolean flag indicating whether the deployment is a rollback deployment.
     */
    @Generated
    @JsonProperty(value = "isCloudInitiatedRollback", access = JsonProperty.Access.WRITE_ONLY)
    private Boolean isCloudInitiatedRollback;

    /**
     * Creates an instance of Deployment class.
     * 
     * @param startDateTime the startDateTime value to set.
     * @param update the update value to set.
     * @param groupId the groupId value to set.
     */
    @Generated
    @JsonCreator
    public Deployment(@JsonProperty(value = "startDateTime") OffsetDateTime startDateTime,
        @JsonProperty(value = "update") UpdateInfo update, @JsonProperty(value = "groupId") String groupId) {
        this.startDateTime = startDateTime;
        this.update = update;
        this.groupId = groupId;
    }

    /**
     * Get the deploymentId property: The caller-provided deployment identifier. This cannot be longer than 73
     * characters, must be all lower-case, and cannot contain '&amp;', '^', '[', ']', '{',
     * '}', '|', '&lt;', '&gt;', forward slash, backslash, or double quote. The Updates view
     * in the Azure Portal IoT Hub resource generates a GUID for deploymentId when you
     * create a deployment.
     * 
     * @return the deploymentId value.
     */
    @Generated
    public String getDeploymentId() {
        return this.deploymentId;
    }

    /**
     * Get the startDateTime property: The deployment start datetime.
     * 
     * @return the startDateTime value.
     */
    @Generated
    public OffsetDateTime getStartDateTime() {
        return this.startDateTime;
    }

    /**
     * Get the update property: Update information for the update in the deployment.
     * 
     * @return the update value.
     */
    @Generated
    public UpdateInfo getUpdate() {
        return this.update;
    }

    /**
     * Get the groupId property: The group identity for the devices the deployment is intended to update.
     * 
     * @return the groupId value.
     */
    @Generated
    public String getGroupId() {
        return this.groupId;
    }

    /**
     * Get the deviceClassSubgroups property: The device class subgroups the deployment is compatible with and subgroup
     * deployments have been created for. This is not provided by the caller during
     * CreateOrUpdateDeployment but is automatically determined by Device Update.
     * 
     * @return the deviceClassSubgroups value.
     */
    @Generated
    public List<String> getDeviceClassSubgroups() {
        return this.deviceClassSubgroups;
    }

    /**
     * Get the isCanceled property: Boolean flag indicating whether the deployment was canceled.
     * 
     * @return the isCanceled value.
     */
    @Generated
    public Boolean isCanceled() {
        return this.isCanceled;
    }

    /**
     * Get the isRetried property: Boolean flag indicating whether the deployment has been retried.
     * 
     * @return the isRetried value.
     */
    @Generated
    public Boolean isRetried() {
        return this.isRetried;
    }

    /**
     * Get the rollbackPolicy property: The rollback policy for the deployment.
     * 
     * @return the rollbackPolicy value.
     */
    @Generated
    public CloudInitiatedRollbackPolicy getRollbackPolicy() {
        return this.rollbackPolicy;
    }

    /**
     * Set the rollbackPolicy property: The rollback policy for the deployment.
     * 
     * @param rollbackPolicy the rollbackPolicy value to set.
     * @return the Deployment object itself.
     */
    @Generated
    public Deployment setRollbackPolicy(CloudInitiatedRollbackPolicy rollbackPolicy) {
        this.rollbackPolicy = rollbackPolicy;
        return this;
    }

    /**
     * Get the isCloudInitiatedRollback property: Boolean flag indicating whether the deployment is a rollback
     * deployment.
     * 
     * @return the isCloudInitiatedRollback value.
     */
    @Generated
    public Boolean isCloudInitiatedRollback() {
        return this.isCloudInitiatedRollback;
    }
}
