// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.iot.deviceupdate.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.azure.core.models.ResponseError;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * Deployment status metadata.
 */
@Immutable
public final class DeploymentStatus {
    /*
     * The group identity
     */
    @Generated
    @JsonProperty(value = "groupId")
    private String groupId;

    /*
     * The state of the deployment.
     */
    @Generated
    @JsonProperty(value = "deploymentState")
    private DeploymentState deploymentState;

    /*
     * The error details of the Failed state. This is not present if the deployment
     * state is not Failed.
     */
    @Generated
    @JsonProperty(value = "error")
    private ResponseError error;

    /*
     * The collection of device class subgroup status objects
     */
    @Generated
    @JsonProperty(value = "subgroupStatus")
    private List<DeviceClassSubgroupDeploymentStatus> subgroupStatus;

    /**
     * Creates an instance of DeploymentStatus class.
     * 
     * @param groupId the groupId value to set.
     * @param deploymentState the deploymentState value to set.
     * @param subgroupStatus the subgroupStatus value to set.
     */
    @Generated
    @JsonCreator
    private DeploymentStatus(@JsonProperty(value = "groupId") String groupId,
        @JsonProperty(value = "deploymentState") DeploymentState deploymentState,
        @JsonProperty(value = "subgroupStatus") List<DeviceClassSubgroupDeploymentStatus> subgroupStatus) {
        this.groupId = groupId;
        this.deploymentState = deploymentState;
        this.subgroupStatus = subgroupStatus;
    }

    /**
     * Get the groupId property: The group identity.
     * 
     * @return the groupId value.
     */
    @Generated
    public String getGroupId() {
        return this.groupId;
    }

    /**
     * Get the deploymentState property: The state of the deployment.
     * 
     * @return the deploymentState value.
     */
    @Generated
    public DeploymentState getDeploymentState() {
        return this.deploymentState;
    }

    /**
     * Get the error property: The error details of the Failed state. This is not present if the deployment
     * state is not Failed.
     * 
     * @return the error value.
     */
    @Generated
    public ResponseError getError() {
        return this.error;
    }

    /**
     * Get the subgroupStatus property: The collection of device class subgroup status objects.
     * 
     * @return the subgroupStatus value.
     */
    @Generated
    public List<DeviceClassSubgroupDeploymentStatus> getSubgroupStatus() {
        return this.subgroupStatus;
    }
}
