// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.iot.deviceupdate.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.annotation.Generated;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Device class metadata.
 */
@Fluent
public final class DeviceClass {
    /*
     * The device class identifier. This is generated from the model Id and the compat
     * properties reported by the device update agent in the Device Update PnP
     * interface in IoT Hub. It is a hex-encoded SHA1 hash.
     */
    @Generated
    @JsonProperty(value = "deviceClassId", access = JsonProperty.Access.WRITE_ONLY)
    private String deviceClassId;

    /*
     * The device class friendly name. This can be updated by callers after the device
     * class has been automatically created.
     */
    @Generated
    @JsonProperty(value = "friendlyName")
    private String friendlyName;

    /*
     * The device class properties that are used to calculate the device class Id
     */
    @Generated
    @JsonProperty(value = "deviceClassProperties", access = JsonProperty.Access.WRITE_ONLY)
    private DeviceClassProperties deviceClassProperties;

    /*
     * Update that is the highest version compatible with this device class.
     */
    @Generated
    @JsonProperty(value = "bestCompatibleUpdate", access = JsonProperty.Access.WRITE_ONLY)
    private UpdateInfo bestCompatibleUpdate;

    /**
     * Creates an instance of DeviceClass class.
     */
    @Generated
    public DeviceClass() {
    }

    /**
     * Get the deviceClassId property: The device class identifier. This is generated from the model Id and the compat
     * properties reported by the device update agent in the Device Update PnP
     * interface in IoT Hub. It is a hex-encoded SHA1 hash.
     * 
     * @return the deviceClassId value.
     */
    @Generated
    public String getDeviceClassId() {
        return this.deviceClassId;
    }

    /**
     * Get the friendlyName property: The device class friendly name. This can be updated by callers after the device
     * class has been automatically created.
     * 
     * @return the friendlyName value.
     */
    @Generated
    public String getFriendlyName() {
        return this.friendlyName;
    }

    /**
     * Set the friendlyName property: The device class friendly name. This can be updated by callers after the device
     * class has been automatically created.
     * 
     * @param friendlyName the friendlyName value to set.
     * @return the DeviceClass object itself.
     */
    @Generated
    public DeviceClass setFriendlyName(String friendlyName) {
        this.friendlyName = friendlyName;
        return this;
    }

    /**
     * Get the deviceClassProperties property: The device class properties that are used to calculate the device class
     * Id.
     * 
     * @return the deviceClassProperties value.
     */
    @Generated
    public DeviceClassProperties getDeviceClassProperties() {
        return this.deviceClassProperties;
    }

    /**
     * Get the bestCompatibleUpdate property: Update that is the highest version compatible with this device class.
     * 
     * @return the bestCompatibleUpdate value.
     */
    @Generated
    public UpdateInfo getBestCompatibleUpdate() {
        return this.bestCompatibleUpdate;
    }
}
