// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.iot.deviceupdate.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.azure.core.models.ResponseError;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Device class subgroup deployment status metadata.
 */
@Immutable
public final class DeviceClassSubgroupDeploymentStatus {
    /*
     * The group identity
     */
    @Generated
    @JsonProperty(value = "groupId")
    private String groupId;

    /*
     * The device class subgroup identity
     */
    @Generated
    @JsonProperty(value = "deviceClassId")
    private String deviceClassId;

    /*
     * The state of the subgroup deployment.
     */
    @Generated
    @JsonProperty(value = "deploymentState")
    private DeviceClassSubgroupDeploymentState deploymentState;

    /*
     * The error details of the Failed state. This is not present if the deployment
     * state is not Failed.
     */
    @Generated
    @JsonProperty(value = "error")
    private ResponseError error;

    /*
     * The total number of devices in the deployment.
     */
    @Generated
    @JsonProperty(value = "totalDevices")
    private Integer totalDevices;

    /*
     * The number of devices that are currently in deployment.
     */
    @Generated
    @JsonProperty(value = "devicesInProgressCount")
    private Integer devicesInProgressCount;

    /*
     * The number of devices that have completed deployment with a failure.
     */
    @Generated
    @JsonProperty(value = "devicesCompletedFailedCount")
    private Integer devicesCompletedFailedCount;

    /*
     * The number of devices which have successfully completed deployment.
     */
    @Generated
    @JsonProperty(value = "devicesCompletedSucceededCount")
    private Integer devicesCompletedSucceededCount;

    /*
     * The number of devices which have had their deployment canceled.
     */
    @Generated
    @JsonProperty(value = "devicesCanceledCount")
    private Integer devicesCanceledCount;

    /**
     * Creates an instance of DeviceClassSubgroupDeploymentStatus class.
     * 
     * @param groupId the groupId value to set.
     * @param deviceClassId the deviceClassId value to set.
     * @param deploymentState the deploymentState value to set.
     */
    @Generated
    @JsonCreator
    private DeviceClassSubgroupDeploymentStatus(@JsonProperty(value = "groupId") String groupId,
        @JsonProperty(value = "deviceClassId") String deviceClassId,
        @JsonProperty(value = "deploymentState") DeviceClassSubgroupDeploymentState deploymentState) {
        this.groupId = groupId;
        this.deviceClassId = deviceClassId;
        this.deploymentState = deploymentState;
    }

    /**
     * Get the groupId property: The group identity.
     * 
     * @return the groupId value.
     */
    @Generated
    public String getGroupId() {
        return this.groupId;
    }

    /**
     * Get the deviceClassId property: The device class subgroup identity.
     * 
     * @return the deviceClassId value.
     */
    @Generated
    public String getDeviceClassId() {
        return this.deviceClassId;
    }

    /**
     * Get the deploymentState property: The state of the subgroup deployment.
     * 
     * @return the deploymentState value.
     */
    @Generated
    public DeviceClassSubgroupDeploymentState getDeploymentState() {
        return this.deploymentState;
    }

    /**
     * Get the error property: The error details of the Failed state. This is not present if the deployment
     * state is not Failed.
     * 
     * @return the error value.
     */
    @Generated
    public ResponseError getError() {
        return this.error;
    }

    /**
     * Get the totalDevices property: The total number of devices in the deployment.
     * 
     * @return the totalDevices value.
     */
    @Generated
    public Integer getTotalDevices() {
        return this.totalDevices;
    }

    /**
     * Get the devicesInProgressCount property: The number of devices that are currently in deployment.
     * 
     * @return the devicesInProgressCount value.
     */
    @Generated
    public Integer getDevicesInProgressCount() {
        return this.devicesInProgressCount;
    }

    /**
     * Get the devicesCompletedFailedCount property: The number of devices that have completed deployment with a
     * failure.
     * 
     * @return the devicesCompletedFailedCount value.
     */
    @Generated
    public Integer getDevicesCompletedFailedCount() {
        return this.devicesCompletedFailedCount;
    }

    /**
     * Get the devicesCompletedSucceededCount property: The number of devices which have successfully completed
     * deployment.
     * 
     * @return the devicesCompletedSucceededCount value.
     */
    @Generated
    public Integer getDevicesCompletedSucceededCount() {
        return this.devicesCompletedSucceededCount;
    }

    /**
     * Get the devicesCanceledCount property: The number of devices which have had their deployment canceled.
     * 
     * @return the devicesCanceledCount value.
     */
    @Generated
    public Integer getDevicesCanceledCount() {
        return this.devicesCanceledCount;
    }
}
