// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.iot.deviceupdate.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Map;

/**
 * The device class properties that are used to calculate the device class Id.
 */
@Immutable
public final class DeviceClassProperties {
    /*
     * The Device Update agent contract model.
     */
    @Generated
    @JsonProperty(value = "contractModel")
    private ContractModel contractModel;

    /*
     * The compat properties of the device class. This object can be thought of as a
     * set of key-value pairs where the key is the name of the compatibility property
     * and the value is the value of the compatibility property. There will always be
     * at least 1 compat property
     */
    @Generated
    @JsonProperty(value = "compatProperties")
    private Map<String, String> compatProperties;

    /**
     * Creates an instance of DeviceClassProperties class.
     * 
     * @param compatProperties the compatProperties value to set.
     */
    @Generated
    @JsonCreator
    private DeviceClassProperties(@JsonProperty(value = "compatProperties") Map<String, String> compatProperties) {
        this.compatProperties = compatProperties;
    }

    /**
     * Get the contractModel property: The Device Update agent contract model.
     * 
     * @return the contractModel value.
     */
    @Generated
    public ContractModel getContractModel() {
        return this.contractModel;
    }

    /**
     * Get the compatProperties property: The compat properties of the device class. This object can be thought of as a
     * set of key-value pairs where the key is the name of the compatibility property
     * and the value is the value of the compatibility property. There will always be
     * at least 1 compat property.
     * 
     * @return the compatProperties value.
     */
    @Generated
    public Map<String, String> getCompatProperties() {
        return this.compatProperties;
    }
}
