// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.iot.deviceupdate.models;

import com.azure.core.annotation.Generated;
import com.azure.core.util.ExpandableStringEnum;
import com.fasterxml.jackson.annotation.JsonCreator;
import java.util.Collection;

/**
 * Device health state.
 */
public final class DeviceHealthState extends ExpandableStringEnum<DeviceHealthState> {
    /**
     * Agent is healthy.
     */
    @Generated
    public static final DeviceHealthState HEALTHY = fromString("healthy");

    /**
     * Agent is in an unhealthy state.
     */
    @Generated
    public static final DeviceHealthState UNHEALTHY = fromString("unhealthy");

    /**
     * Creates a new instance of DeviceHealthState value.
     * 
     * @deprecated Use the {@link #fromString(String)} factory method.
     */
    @Generated
    @Deprecated
    public DeviceHealthState() {
    }

    /**
     * Creates or finds a DeviceHealthState from its string representation.
     * 
     * @param name a name to look for.
     * @return the corresponding DeviceHealthState.
     */
    @Generated
    @JsonCreator
    public static DeviceHealthState fromString(String name) {
        return fromString(name, DeviceHealthState.class);
    }

    /**
     * Gets known DeviceHealthState values.
     * 
     * @return known DeviceHealthState values.
     */
    @Generated
    public static Collection<DeviceHealthState> values() {
        return values(DeviceHealthState.class);
    }
}
