// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.iot.deviceupdate.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.annotation.Generated;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Device Update agent id.
 */
@Fluent
public final class DeviceUpdateAgentId {
    /*
     * Device Id
     */
    @Generated
    @JsonProperty(value = "deviceId")
    private String deviceId;

    /*
     * Module Id
     */
    @Generated
    @JsonProperty(value = "moduleId")
    private String moduleId;

    /**
     * Creates an instance of DeviceUpdateAgentId class.
     * 
     * @param deviceId the deviceId value to set.
     */
    @Generated
    @JsonCreator
    public DeviceUpdateAgentId(@JsonProperty(value = "deviceId") String deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * Get the deviceId property: Device Id.
     * 
     * @return the deviceId value.
     */
    @Generated
    public String getDeviceId() {
        return this.deviceId;
    }

    /**
     * Get the moduleId property: Module Id.
     * 
     * @return the moduleId value.
     */
    @Generated
    public String getModuleId() {
        return this.moduleId;
    }

    /**
     * Set the moduleId property: Module Id.
     * 
     * @param moduleId the moduleId value to set.
     * @return the DeviceUpdateAgentId object itself.
     */
    @Generated
    public DeviceUpdateAgentId setModuleId(String moduleId) {
        this.moduleId = moduleId;
        return this;
    }
}
