// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.iot.deviceupdate.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Device class subgroup details. A device class subgroup is a subset of devices
 * in a group that share the same device class id.
 */
@Immutable
public final class DeviceClassSubgroup {
    /*
     * Device class subgroup identity. This is generated from the model Id and the
     * compat properties reported by the device update agent in the Device Update PnP
     * interface in IoT Hub. It is a hex-encoded SHA1 hash.
     */
    @Generated
    @JsonProperty(value = "deviceClassId", access = JsonProperty.Access.WRITE_ONLY)
    private String deviceClassId;

    /*
     * Group identity.
     */
    @Generated
    @JsonProperty(value = "groupId")
    private String groupId;

    /*
     * Date and time when the device class subgroup was created.
     */
    @Generated
    @JsonProperty(value = "createdDateTime")
    private String createdDateTime;

    /*
     * The number of devices in the device class subgroup.
     */
    @Generated
    @JsonProperty(value = "deviceCount")
    private Integer deviceCount;

    /*
     * The active deployment Id for the device class subgroup.
     */
    @Generated
    @JsonProperty(value = "deploymentId")
    private String deploymentId;

    /**
     * Creates an instance of DeviceClassSubgroup class.
     * 
     * @param groupId the groupId value to set.
     * @param createdDateTime the createdDateTime value to set.
     */
    @Generated
    @JsonCreator
    private DeviceClassSubgroup(@JsonProperty(value = "groupId") String groupId,
        @JsonProperty(value = "createdDateTime") String createdDateTime) {
        this.groupId = groupId;
        this.createdDateTime = createdDateTime;
    }

    /**
     * Get the deviceClassId property: Device class subgroup identity. This is generated from the model Id and the
     * compat properties reported by the device update agent in the Device Update PnP
     * interface in IoT Hub. It is a hex-encoded SHA1 hash.
     * 
     * @return the deviceClassId value.
     */
    @Generated
    public String getDeviceClassId() {
        return this.deviceClassId;
    }

    /**
     * Get the groupId property: Group identity.
     * 
     * @return the groupId value.
     */
    @Generated
    public String getGroupId() {
        return this.groupId;
    }

    /**
     * Get the createdDateTime property: Date and time when the device class subgroup was created.
     * 
     * @return the createdDateTime value.
     */
    @Generated
    public String getCreatedDateTime() {
        return this.createdDateTime;
    }

    /**
     * Get the deviceCount property: The number of devices in the device class subgroup.
     * 
     * @return the deviceCount value.
     */
    @Generated
    public Integer getDeviceCount() {
        return this.deviceCount;
    }

    /**
     * Get the deploymentId property: The active deployment Id for the device class subgroup.
     * 
     * @return the deploymentId value.
     */
    @Generated
    public String getDeploymentId() {
        return this.deploymentId;
    }
}
