// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.iot.deviceupdate.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.azure.core.models.ResponseError;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;

/**
 * Operation metadata.
 */
@Immutable
public final class DeviceOperation {
    /*
     * Operation Id.
     */
    @Generated
    @JsonProperty(value = "operationId", access = JsonProperty.Access.WRITE_ONLY)
    private String operationId;

    /*
     * Operation status.
     */
    @Generated
    @JsonProperty(value = "status")
    private OperationStatus status;

    /*
     * Operation error encountered, if any.
     */
    @Generated
    @JsonProperty(value = "error")
    private ResponseError error;

    /*
     * Operation correlation identity that can used by Microsoft Support for troubleshooting.
     */
    @Generated
    @JsonProperty(value = "traceId")
    private String traceId;

    /*
     * Date and time in UTC when the operation status was last updated.
     */
    @Generated
    @JsonProperty(value = "lastActionDateTime")
    private OffsetDateTime lastActionDateTime;

    /*
     * Date and time in UTC when the operation was created.
     */
    @Generated
    @JsonProperty(value = "createdDateTime")
    private OffsetDateTime createdDateTime;

    /*
     * Operation ETag.
     */
    @Generated
    @JsonProperty(value = "etag")
    private String etag;

    /**
     * Creates an instance of DeviceOperation class.
     * 
     * @param status the status value to set.
     * @param lastActionDateTime the lastActionDateTime value to set.
     * @param createdDateTime the createdDateTime value to set.
     */
    @Generated
    @JsonCreator
    private DeviceOperation(@JsonProperty(value = "status") OperationStatus status,
        @JsonProperty(value = "lastActionDateTime") OffsetDateTime lastActionDateTime,
        @JsonProperty(value = "createdDateTime") OffsetDateTime createdDateTime) {
        this.status = status;
        this.lastActionDateTime = lastActionDateTime;
        this.createdDateTime = createdDateTime;
    }

    /**
     * Get the operationId property: Operation Id.
     * 
     * @return the operationId value.
     */
    @Generated
    public String getOperationId() {
        return this.operationId;
    }

    /**
     * Get the status property: Operation status.
     * 
     * @return the status value.
     */
    @Generated
    public OperationStatus getStatus() {
        return this.status;
    }

    /**
     * Get the error property: Operation error encountered, if any.
     * 
     * @return the error value.
     */
    @Generated
    public ResponseError getError() {
        return this.error;
    }

    /**
     * Get the traceId property: Operation correlation identity that can used by Microsoft Support for troubleshooting.
     * 
     * @return the traceId value.
     */
    @Generated
    public String getTraceId() {
        return this.traceId;
    }

    /**
     * Get the lastActionDateTime property: Date and time in UTC when the operation status was last updated.
     * 
     * @return the lastActionDateTime value.
     */
    @Generated
    public OffsetDateTime getLastActionDateTime() {
        return this.lastActionDateTime;
    }

    /**
     * Get the createdDateTime property: Date and time in UTC when the operation was created.
     * 
     * @return the createdDateTime value.
     */
    @Generated
    public OffsetDateTime getCreatedDateTime() {
        return this.createdDateTime;
    }

    /**
     * Get the etag property: Operation ETag.
     * 
     * @return the etag value.
     */
    @Generated
    public String getEtag() {
        return this.etag;
    }
}
