// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.iot.deviceupdate.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Device metadata.
 */
@Immutable
public final class Device {
    /*
     * Device identity.
     */
    @Generated
    @JsonProperty(value = "deviceId", access = JsonProperty.Access.WRITE_ONLY)
    private String deviceId;

    /*
     * Device module identity.
     */
    @Generated
    @JsonProperty(value = "moduleId")
    private String moduleId;

    /*
     * Device class identity.
     */
    @Generated
    @JsonProperty(value = "deviceClassId")
    private String deviceClassId;

    /*
     * Device group identity.
     */
    @Generated
    @JsonProperty(value = "groupId")
    private String groupId;

    /*
     * The update that device last attempted to install.
     */
    @Generated
    @JsonProperty(value = "lastAttemptedUpdate")
    private UpdateInfo lastAttemptedUpdate;

    /*
     * State of the device in its last deployment.
     */
    @Generated
    @JsonProperty(value = "deploymentStatus")
    private DeviceDeploymentState deploymentStatus;

    /*
     * Currently installed update on device.
     */
    @Generated
    @JsonProperty(value = "installedUpdate")
    private UpdateInfo installedUpdate;

    /*
     * Boolean flag indicating whether the latest update (the best compatible update
     * for the device's device class and group) is installed on the device
     */
    @Generated
    @JsonProperty(value = "onLatestUpdate")
    private boolean onLatestUpdate;

    /*
     * The deployment identifier for the last deployment to the device
     */
    @Generated
    @JsonProperty(value = "lastDeploymentId")
    private String lastDeploymentId;

    /*
     * Last install result.
     */
    @Generated
    @JsonProperty(value = "lastInstallResult")
    private InstallResult lastInstallResult;

    /**
     * Creates an instance of Device class.
     * 
     * @param deviceClassId the deviceClassId value to set.
     * @param onLatestUpdate the onLatestUpdate value to set.
     */
    @Generated
    @JsonCreator
    private Device(@JsonProperty(value = "deviceClassId") String deviceClassId,
        @JsonProperty(value = "onLatestUpdate") boolean onLatestUpdate) {
        this.deviceClassId = deviceClassId;
        this.onLatestUpdate = onLatestUpdate;
    }

    /**
     * Get the deviceId property: Device identity.
     * 
     * @return the deviceId value.
     */
    @Generated
    public String getDeviceId() {
        return this.deviceId;
    }

    /**
     * Get the moduleId property: Device module identity.
     * 
     * @return the moduleId value.
     */
    @Generated
    public String getModuleId() {
        return this.moduleId;
    }

    /**
     * Get the deviceClassId property: Device class identity.
     * 
     * @return the deviceClassId value.
     */
    @Generated
    public String getDeviceClassId() {
        return this.deviceClassId;
    }

    /**
     * Get the groupId property: Device group identity.
     * 
     * @return the groupId value.
     */
    @Generated
    public String getGroupId() {
        return this.groupId;
    }

    /**
     * Get the lastAttemptedUpdate property: The update that device last attempted to install.
     * 
     * @return the lastAttemptedUpdate value.
     */
    @Generated
    public UpdateInfo getLastAttemptedUpdate() {
        return this.lastAttemptedUpdate;
    }

    /**
     * Get the deploymentStatus property: State of the device in its last deployment.
     * 
     * @return the deploymentStatus value.
     */
    @Generated
    public DeviceDeploymentState getDeploymentStatus() {
        return this.deploymentStatus;
    }

    /**
     * Get the installedUpdate property: Currently installed update on device.
     * 
     * @return the installedUpdate value.
     */
    @Generated
    public UpdateInfo getInstalledUpdate() {
        return this.installedUpdate;
    }

    /**
     * Get the onLatestUpdate property: Boolean flag indicating whether the latest update (the best compatible update
     * for the device's device class and group) is installed on the device.
     * 
     * @return the onLatestUpdate value.
     */
    @Generated
    public boolean isOnLatestUpdate() {
        return this.onLatestUpdate;
    }

    /**
     * Get the lastDeploymentId property: The deployment identifier for the last deployment to the device.
     * 
     * @return the lastDeploymentId value.
     */
    @Generated
    public String getLastDeploymentId() {
        return this.lastDeploymentId;
    }

    /**
     * Get the lastInstallResult property: Last install result.
     * 
     * @return the lastInstallResult value.
     */
    @Generated
    public InstallResult getLastInstallResult() {
        return this.lastInstallResult;
    }
}
