// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.iot.deviceupdate.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * Device Health.
 */
@Immutable
public final class DeviceHealth {
    /*
     * Device id
     */
    @Generated
    @JsonProperty(value = "deviceId", access = JsonProperty.Access.WRITE_ONLY)
    private String deviceId;

    /*
     * Module id
     */
    @Generated
    @JsonProperty(value = "moduleId")
    private String moduleId;

    /*
     * Aggregate device health state
     */
    @Generated
    @JsonProperty(value = "state")
    private DeviceHealthState state;

    /*
     * Digital twin model Id
     */
    @Generated
    @JsonProperty(value = "digitalTwinModelId")
    private String digitalTwinModelId;

    /*
     * Array of health checks and their results
     */
    @Generated
    @JsonProperty(value = "healthChecks")
    private List<HealthCheck> healthChecks;

    /**
     * Creates an instance of DeviceHealth class.
     * 
     * @param state the state value to set.
     * @param healthChecks the healthChecks value to set.
     */
    @Generated
    @JsonCreator
    private DeviceHealth(@JsonProperty(value = "state") DeviceHealthState state,
        @JsonProperty(value = "healthChecks") List<HealthCheck> healthChecks) {
        this.state = state;
        this.healthChecks = healthChecks;
    }

    /**
     * Get the deviceId property: Device id.
     * 
     * @return the deviceId value.
     */
    @Generated
    public String getDeviceId() {
        return this.deviceId;
    }

    /**
     * Get the moduleId property: Module id.
     * 
     * @return the moduleId value.
     */
    @Generated
    public String getModuleId() {
        return this.moduleId;
    }

    /**
     * Get the state property: Aggregate device health state.
     * 
     * @return the state value.
     */
    @Generated
    public DeviceHealthState getState() {
        return this.state;
    }

    /**
     * Get the digitalTwinModelId property: Digital twin model Id.
     * 
     * @return the digitalTwinModelId value.
     */
    @Generated
    public String getDigitalTwinModelId() {
        return this.digitalTwinModelId;
    }

    /**
     * Get the healthChecks property: Array of health checks and their results.
     * 
     * @return the healthChecks value.
     */
    @Generated
    public List<HealthCheck> getHealthChecks() {
        return this.healthChecks;
    }
}
