// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.iot.deviceupdate.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Device class subgroup, update information, and the number of devices for which the update is applicable.
 */
@Immutable
public final class DeviceClassSubgroupUpdatableDevices {
    /*
     * The group Id
     */
    @Generated
    @JsonProperty(value = "groupId")
    private String groupId;

    /*
     * The device class subgroup's device class Id
     */
    @Generated
    @JsonProperty(value = "deviceClassId")
    private String deviceClassId;

    /*
     * Update information.
     */
    @Generated
    @JsonProperty(value = "update")
    private UpdateInfo update;

    /*
     * Total number of devices for which the update is applicable.
     */
    @Generated
    @JsonProperty(value = "deviceCount")
    private int deviceCount;

    /**
     * Creates an instance of DeviceClassSubgroupUpdatableDevices class.
     * 
     * @param groupId the groupId value to set.
     * @param deviceClassId the deviceClassId value to set.
     * @param update the update value to set.
     * @param deviceCount the deviceCount value to set.
     */
    @Generated
    @JsonCreator
    private DeviceClassSubgroupUpdatableDevices(@JsonProperty(value = "groupId") String groupId,
        @JsonProperty(value = "deviceClassId") String deviceClassId, @JsonProperty(value = "update") UpdateInfo update,
        @JsonProperty(value = "deviceCount") int deviceCount) {
        this.groupId = groupId;
        this.deviceClassId = deviceClassId;
        this.update = update;
        this.deviceCount = deviceCount;
    }

    /**
     * Get the groupId property: The group Id.
     * 
     * @return the groupId value.
     */
    @Generated
    public String getGroupId() {
        return this.groupId;
    }

    /**
     * Get the deviceClassId property: The device class subgroup's device class Id.
     * 
     * @return the deviceClassId value.
     */
    @Generated
    public String getDeviceClassId() {
        return this.deviceClassId;
    }

    /**
     * Get the update property: Update information.
     * 
     * @return the update value.
     */
    @Generated
    public UpdateInfo getUpdate() {
        return this.update;
    }

    /**
     * Get the deviceCount property: Total number of devices for which the update is applicable.
     * 
     * @return the deviceCount value.
     */
    @Generated
    public int getDeviceCount() {
        return this.deviceCount;
    }
}
