// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.iot.deviceupdate.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Metadata describing an update file.
 */
@Immutable
public final class FileImportMetadata {
    /*
     * Update file name as specified inside import manifest.
     */
    @Generated
    @JsonProperty(value = "filename")
    private String filename;

    /*
     * Azure Blob location from which the update file can be downloaded by Device
     * Update for IoT Hub. This is typically a read-only SAS-protected blob URL with
     * an expiration set to at least 4 hours.
     */
    @Generated
    @JsonProperty(value = "url")
    private String url;

    /**
     * Creates an instance of FileImportMetadata class.
     * 
     * @param filename the filename value to set.
     * @param url the url value to set.
     */
    @Generated
    @JsonCreator
    public FileImportMetadata(@JsonProperty(value = "filename") String filename,
        @JsonProperty(value = "url") String url) {
        this.filename = filename;
        this.url = url;
    }

    /**
     * Get the filename property: Update file name as specified inside import manifest.
     * 
     * @return the filename value.
     */
    @Generated
    public String getFilename() {
        return this.filename;
    }

    /**
     * Get the url property: Azure Blob location from which the update file can be downloaded by Device
     * Update for IoT Hub. This is typically a read-only SAS-protected blob URL with
     * an expiration set to at least 4 hours.
     * 
     * @return the url value.
     */
    @Generated
    public String getUrl() {
        return this.url;
    }
}
