// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.iot.deviceupdate.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * Group details.
 */
@Immutable
public final class Group {
    /*
     * Group identity. This is created from the value of the ADUGroup tag in the Iot
     * Hub's device/module twin or $default for devices with no tag.
     */
    @Generated
    @JsonProperty(value = "groupId", access = JsonProperty.Access.WRITE_ONLY)
    private String groupId;

    /*
     * Group type.
     */
    @Generated
    @JsonProperty(value = "groupType")
    private GroupType groupType;

    /*
     * Date and time when the update was created.
     */
    @Generated
    @JsonProperty(value = "createdDateTime")
    private String createdDateTime;

    /*
     * The number of devices in the group.
     */
    @Generated
    @JsonProperty(value = "deviceCount")
    private Integer deviceCount;

    /*
     * The count of subgroups with new updates available.
     */
    @Generated
    @JsonProperty(value = "subgroupsWithNewUpdatesAvailableCount")
    private Integer subgroupsWithNewUpdatesAvailableCount;

    /*
     * The count of subgroups with updates in progress.
     */
    @Generated
    @JsonProperty(value = "subgroupsWithUpdatesInProgressCount")
    private Integer subgroupsWithUpdatesInProgressCount;

    /*
     * The count of subgroups with devices on the latest update.
     */
    @Generated
    @JsonProperty(value = "subgroupsWithOnLatestUpdateCount")
    private Integer subgroupsWithOnLatestUpdateCount;

    /*
     * The active deployment Ids for the group
     */
    @Generated
    @JsonProperty(value = "deployments")
    private List<String> deployments;

    /**
     * Creates an instance of Group class.
     * 
     * @param groupType the groupType value to set.
     * @param createdDateTime the createdDateTime value to set.
     */
    @Generated
    @JsonCreator
    private Group(@JsonProperty(value = "groupType") GroupType groupType,
        @JsonProperty(value = "createdDateTime") String createdDateTime) {
        this.groupType = groupType;
        this.createdDateTime = createdDateTime;
    }

    /**
     * Get the groupId property: Group identity. This is created from the value of the ADUGroup tag in the Iot
     * Hub's device/module twin or $default for devices with no tag.
     * 
     * @return the groupId value.
     */
    @Generated
    public String getGroupId() {
        return this.groupId;
    }

    /**
     * Get the groupType property: Group type.
     * 
     * @return the groupType value.
     */
    @Generated
    public GroupType getGroupType() {
        return this.groupType;
    }

    /**
     * Get the createdDateTime property: Date and time when the update was created.
     * 
     * @return the createdDateTime value.
     */
    @Generated
    public String getCreatedDateTime() {
        return this.createdDateTime;
    }

    /**
     * Get the deviceCount property: The number of devices in the group.
     * 
     * @return the deviceCount value.
     */
    @Generated
    public Integer getDeviceCount() {
        return this.deviceCount;
    }

    /**
     * Get the subgroupsWithNewUpdatesAvailableCount property: The count of subgroups with new updates available.
     * 
     * @return the subgroupsWithNewUpdatesAvailableCount value.
     */
    @Generated
    public Integer getSubgroupsWithNewUpdatesAvailableCount() {
        return this.subgroupsWithNewUpdatesAvailableCount;
    }

    /**
     * Get the subgroupsWithUpdatesInProgressCount property: The count of subgroups with updates in progress.
     * 
     * @return the subgroupsWithUpdatesInProgressCount value.
     */
    @Generated
    public Integer getSubgroupsWithUpdatesInProgressCount() {
        return this.subgroupsWithUpdatesInProgressCount;
    }

    /**
     * Get the subgroupsWithOnLatestUpdateCount property: The count of subgroups with devices on the latest update.
     * 
     * @return the subgroupsWithOnLatestUpdateCount value.
     */
    @Generated
    public Integer getSubgroupsWithOnLatestUpdateCount() {
        return this.subgroupsWithOnLatestUpdateCount;
    }

    /**
     * Get the deployments property: The active deployment Ids for the group.
     * 
     * @return the deployments value.
     */
    @Generated
    public List<String> getDeployments() {
        return this.deployments;
    }
}
