// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.iot.deviceupdate.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Health check.
 */
@Immutable
public final class HealthCheck {
    /*
     * Health check name
     */
    @Generated
    @JsonProperty(value = "name")
    private String name;

    /*
     * Health check result
     */
    @Generated
    @JsonProperty(value = "result")
    private HealthCheckResult result;

    /**
     * Creates an instance of HealthCheck class.
     */
    @Generated
    private HealthCheck() {
    }

    /**
     * Get the name property: Health check name.
     * 
     * @return the name value.
     */
    @Generated
    public String getName() {
        return this.name;
    }

    /**
     * Get the result property: Health check result.
     * 
     * @return the result value.
     */
    @Generated
    public HealthCheckResult getResult() {
        return this.result;
    }
}
