// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.iot.deviceupdate.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Map;

/**
 * Metadata describing the import manifest, a document which describes the files
 * and other metadata about an update version.
 */
@Immutable
public final class ImportManifestMetadata {
    /*
     * Azure Blob location from which the import manifest can be downloaded by Device
     * Update for IoT Hub. This is typically a read-only SAS-protected blob URL with
     * an expiration set to at least 4 hours.
     */
    @Generated
    @JsonProperty(value = "url")
    private String url;

    /*
     * File size in number of bytes.
     */
    @Generated
    @JsonProperty(value = "sizeInBytes")
    private long sizeInBytes;

    /*
     * A JSON object containing the hash(es) of the file. At least SHA256 hash is
     * required. This object can be thought of as a set of key-value pairs where the
     * key is the hash algorithm, and the value is the hash of the file calculated
     * using that algorithm.
     */
    @Generated
    @JsonProperty(value = "hashes")
    private Map<String, String> hashes;

    /**
     * Creates an instance of ImportManifestMetadata class.
     * 
     * @param url the url value to set.
     * @param sizeInBytes the sizeInBytes value to set.
     * @param hashes the hashes value to set.
     */
    @Generated
    @JsonCreator
    public ImportManifestMetadata(@JsonProperty(value = "url") String url,
        @JsonProperty(value = "sizeInBytes") long sizeInBytes,
        @JsonProperty(value = "hashes") Map<String, String> hashes) {
        this.url = url;
        this.sizeInBytes = sizeInBytes;
        this.hashes = hashes;
    }

    /**
     * Get the url property: Azure Blob location from which the import manifest can be downloaded by Device
     * Update for IoT Hub. This is typically a read-only SAS-protected blob URL with
     * an expiration set to at least 4 hours.
     * 
     * @return the url value.
     */
    @Generated
    public String getUrl() {
        return this.url;
    }

    /**
     * Get the sizeInBytes property: File size in number of bytes.
     * 
     * @return the sizeInBytes value.
     */
    @Generated
    public long getSizeInBytes() {
        return this.sizeInBytes;
    }

    /**
     * Get the hashes property: A JSON object containing the hash(es) of the file. At least SHA256 hash is
     * required. This object can be thought of as a set of key-value pairs where the
     * key is the hash algorithm, and the value is the hash of the file calculated
     * using that algorithm.
     * 
     * @return the hashes value.
     */
    @Generated
    public Map<String, String> getHashes() {
        return this.hashes;
    }
}
