// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.iot.deviceupdate.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.annotation.Generated;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * Import update input item metadata.
 */
@Fluent
public final class ImportUpdateInputItem {
    /*
     * Import manifest metadata like source URL, file size/hashes, etc.
     */
    @Generated
    @JsonProperty(value = "importManifest")
    private ImportManifestMetadata importManifest;

    /*
     * Friendly update name.
     */
    @Generated
    @JsonProperty(value = "friendlyName")
    private String friendlyName;

    /*
     * One or more update file properties like filename and source URL.
     */
    @Generated
    @JsonProperty(value = "files")
    private List<FileImportMetadata> files;

    /**
     * Creates an instance of ImportUpdateInputItem class.
     * 
     * @param importManifest the importManifest value to set.
     */
    @Generated
    @JsonCreator
    public ImportUpdateInputItem(@JsonProperty(value = "importManifest") ImportManifestMetadata importManifest) {
        this.importManifest = importManifest;
    }

    /**
     * Get the importManifest property: Import manifest metadata like source URL, file size/hashes, etc.
     * 
     * @return the importManifest value.
     */
    @Generated
    public ImportManifestMetadata getImportManifest() {
        return this.importManifest;
    }

    /**
     * Get the friendlyName property: Friendly update name.
     * 
     * @return the friendlyName value.
     */
    @Generated
    public String getFriendlyName() {
        return this.friendlyName;
    }

    /**
     * Set the friendlyName property: Friendly update name.
     * 
     * @param friendlyName the friendlyName value to set.
     * @return the ImportUpdateInputItem object itself.
     */
    @Generated
    public ImportUpdateInputItem setFriendlyName(String friendlyName) {
        this.friendlyName = friendlyName;
        return this;
    }

    /**
     * Get the files property: One or more update file properties like filename and source URL.
     * 
     * @return the files value.
     */
    @Generated
    public List<FileImportMetadata> getFiles() {
        return this.files;
    }

    /**
     * Set the files property: One or more update file properties like filename and source URL.
     * 
     * @param files the files value to set.
     * @return the ImportUpdateInputItem object itself.
     */
    @Generated
    public ImportUpdateInputItem setFiles(List<FileImportMetadata> files) {
        this.files = files;
        return this;
    }
}
