// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.iot.deviceupdate.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * The install result of an update and any step results under it.
 */
@Immutable
public final class InstallResult {
    /*
     * Install result code.
     */
    @Generated
    @JsonProperty(value = "resultCode")
    private int resultCode;

    /*
     * Install extended result code
     */
    @Generated
    @JsonProperty(value = "extendedResultCode")
    private int extendedResultCode;

    /*
     * A string containing further details about the install result
     */
    @Generated
    @JsonProperty(value = "resultDetails")
    private String resultDetails;

    /*
     * Array of step results
     */
    @Generated
    @JsonProperty(value = "stepResults")
    private List<StepResult> stepResults;

    /**
     * Creates an instance of InstallResult class.
     * 
     * @param resultCode the resultCode value to set.
     * @param extendedResultCode the extendedResultCode value to set.
     */
    @Generated
    @JsonCreator
    private InstallResult(@JsonProperty(value = "resultCode") int resultCode,
        @JsonProperty(value = "extendedResultCode") int extendedResultCode) {
        this.resultCode = resultCode;
        this.extendedResultCode = extendedResultCode;
    }

    /**
     * Get the resultCode property: Install result code.
     * 
     * @return the resultCode value.
     */
    @Generated
    public int getResultCode() {
        return this.resultCode;
    }

    /**
     * Get the extendedResultCode property: Install extended result code.
     * 
     * @return the extendedResultCode value.
     */
    @Generated
    public int getExtendedResultCode() {
        return this.extendedResultCode;
    }

    /**
     * Get the resultDetails property: A string containing further details about the install result.
     * 
     * @return the resultDetails value.
     */
    @Generated
    public String getResultDetails() {
        return this.resultDetails;
    }

    /**
     * Get the stepResults property: Array of step results.
     * 
     * @return the stepResults value.
     */
    @Generated
    public List<StepResult> getStepResults() {
        return this.stepResults;
    }
}
