// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.iot.deviceupdate.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * Update installation instructions.
 */
@Immutable
public final class Instructions {
    /*
     * Collection of installation steps.
     */
    @Generated
    @JsonProperty(value = "steps")
    private List<Step> steps;

    /**
     * Creates an instance of Instructions class.
     * 
     * @param steps the steps value to set.
     */
    @Generated
    @JsonCreator
    private Instructions(@JsonProperty(value = "steps") List<Step> steps) {
        this.steps = steps;
    }

    /**
     * Get the steps property: Collection of installation steps.
     * 
     * @return the steps value.
     */
    @Generated
    public List<Step> getSteps() {
        return this.steps;
    }
}
