// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.iot.deviceupdate.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The list of limits of how many of each resource are currently in use and how
 * many are allowed.
 */
@Immutable
public final class Limits {
    /*
     * The list of current counts of each limited resource and the maximum quota that are allowed.
     */
    @Generated
    @JsonProperty(value = "counters")
    private Counters counters;

    /**
     * Creates an instance of Limits class.
     * 
     * @param counters the counters value to set.
     */
    @Generated
    @JsonCreator
    private Limits(@JsonProperty(value = "counters") Counters counters) {
        this.counters = counters;
    }

    /**
     * Get the counters property: The list of current counts of each limited resource and the maximum quota that are
     * allowed.
     * 
     * @return the counters value.
     */
    @Generated
    public Counters getCounters() {
        return this.counters;
    }
}
