// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.iot.deviceupdate.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Diagnostics operation device status.
 */
@Immutable
public final class LogCollectionOperationDeviceStatus {
    /*
     * Device id
     */
    @Generated
    @JsonProperty(value = "deviceId")
    private String deviceId;

    /*
     * Module id.
     */
    @Generated
    @JsonProperty(value = "moduleId")
    private String moduleId;

    /*
     * Log upload status
     */
    @Generated
    @JsonProperty(value = "status")
    private OperationStatus status;

    /*
     * Log upload result code
     */
    @Generated
    @JsonProperty(value = "resultCode")
    private String resultCode;

    /*
     * Log upload extended result code
     */
    @Generated
    @JsonProperty(value = "extendedResultCode")
    private String extendedResultCode;

    /*
     * Log upload location
     */
    @Generated
    @JsonProperty(value = "logLocation")
    private String logLocation;

    /**
     * Creates an instance of LogCollectionOperationDeviceStatus class.
     * 
     * @param deviceId the deviceId value to set.
     * @param status the status value to set.
     */
    @Generated
    @JsonCreator
    private LogCollectionOperationDeviceStatus(@JsonProperty(value = "deviceId") String deviceId,
        @JsonProperty(value = "status") OperationStatus status) {
        this.deviceId = deviceId;
        this.status = status;
    }

    /**
     * Get the deviceId property: Device id.
     * 
     * @return the deviceId value.
     */
    @Generated
    public String getDeviceId() {
        return this.deviceId;
    }

    /**
     * Get the moduleId property: Module id.
     * 
     * @return the moduleId value.
     */
    @Generated
    public String getModuleId() {
        return this.moduleId;
    }

    /**
     * Get the status property: Log upload status.
     * 
     * @return the status value.
     */
    @Generated
    public OperationStatus getStatus() {
        return this.status;
    }

    /**
     * Get the resultCode property: Log upload result code.
     * 
     * @return the resultCode value.
     */
    @Generated
    public String getResultCode() {
        return this.resultCode;
    }

    /**
     * Get the extendedResultCode property: Log upload extended result code.
     * 
     * @return the extendedResultCode value.
     */
    @Generated
    public String getExtendedResultCode() {
        return this.extendedResultCode;
    }

    /**
     * Get the logLocation property: Log upload location.
     * 
     * @return the logLocation value.
     */
    @Generated
    public String getLogLocation() {
        return this.logLocation;
    }
}
