// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.iot.deviceupdate.models;

import com.azure.core.annotation.Fluent;
import com.azure.core.annotation.Generated;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * Diagnostics request body.
 */
@Fluent
public final class LogCollection {
    /*
     * The log collection id.
     */
    @Generated
    @JsonProperty(value = "operationId", access = JsonProperty.Access.WRITE_ONLY)
    private String operationId;

    /*
     * Array of Device Update agent ids
     */
    @Generated
    @JsonProperty(value = "deviceList")
    private List<DeviceUpdateAgentId> deviceList;

    /*
     * Description of the diagnostics operation.
     */
    @Generated
    @JsonProperty(value = "description")
    private String description;

    /*
     * The timestamp when the operation was created.
     */
    @Generated
    @JsonProperty(value = "createdDateTime", access = JsonProperty.Access.WRITE_ONLY)
    private String createdDateTime;

    /*
     * A timestamp for when the current state was entered.
     */
    @Generated
    @JsonProperty(value = "lastActionDateTime", access = JsonProperty.Access.WRITE_ONLY)
    private String lastActionDateTime;

    /*
     * Operation status.
     */
    @Generated
    @JsonProperty(value = "status", access = JsonProperty.Access.WRITE_ONLY)
    private OperationStatus status;

    /**
     * Creates an instance of LogCollection class.
     * 
     * @param deviceList the deviceList value to set.
     */
    @Generated
    @JsonCreator
    public LogCollection(@JsonProperty(value = "deviceList") List<DeviceUpdateAgentId> deviceList) {
        this.deviceList = deviceList;
    }

    /**
     * Get the operationId property: The log collection id.
     * 
     * @return the operationId value.
     */
    @Generated
    public String getOperationId() {
        return this.operationId;
    }

    /**
     * Get the deviceList property: Array of Device Update agent ids.
     * 
     * @return the deviceList value.
     */
    @Generated
    public List<DeviceUpdateAgentId> getDeviceList() {
        return this.deviceList;
    }

    /**
     * Get the description property: Description of the diagnostics operation.
     * 
     * @return the description value.
     */
    @Generated
    public String getDescription() {
        return this.description;
    }

    /**
     * Set the description property: Description of the diagnostics operation.
     * 
     * @param description the description value to set.
     * @return the LogCollection object itself.
     */
    @Generated
    public LogCollection setDescription(String description) {
        this.description = description;
        return this;
    }

    /**
     * Get the createdDateTime property: The timestamp when the operation was created.
     * 
     * @return the createdDateTime value.
     */
    @Generated
    public String getCreatedDateTime() {
        return this.createdDateTime;
    }

    /**
     * Get the lastActionDateTime property: A timestamp for when the current state was entered.
     * 
     * @return the lastActionDateTime value.
     */
    @Generated
    public String getLastActionDateTime() {
        return this.lastActionDateTime;
    }

    /**
     * Get the status property: Operation status.
     * 
     * @return the status value.
     */
    @Generated
    public OperationStatus getStatus() {
        return this.status;
    }
}
