// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.iot.deviceupdate.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.List;

/**
 * Device diagnostics operation detailed status.
 */
@Immutable
public final class LogCollectionOperationDetailedStatus {
    /*
     * The device diagnostics operation id.
     */
    @Generated
    @JsonProperty(value = "operationId")
    private String operationId;

    /*
     * The timestamp when the operation was created.
     */
    @Generated
    @JsonProperty(value = "createdDateTime")
    private String createdDateTime;

    /*
     * A timestamp for when the current state was entered.
     */
    @Generated
    @JsonProperty(value = "lastActionDateTime")
    private String lastActionDateTime;

    /*
     * Operation status.
     */
    @Generated
    @JsonProperty(value = "status")
    private OperationStatus status;

    /*
     * Status of the devices in the operation
     */
    @Generated
    @JsonProperty(value = "deviceStatus")
    private List<LogCollectionOperationDeviceStatus> deviceStatus;

    /*
     * Device diagnostics operation description.
     */
    @Generated
    @JsonProperty(value = "description")
    private String description;

    /**
     * Creates an instance of LogCollectionOperationDetailedStatus class.
     */
    @Generated
    private LogCollectionOperationDetailedStatus() {
    }

    /**
     * Get the operationId property: The device diagnostics operation id.
     * 
     * @return the operationId value.
     */
    @Generated
    public String getOperationId() {
        return this.operationId;
    }

    /**
     * Get the createdDateTime property: The timestamp when the operation was created.
     * 
     * @return the createdDateTime value.
     */
    @Generated
    public String getCreatedDateTime() {
        return this.createdDateTime;
    }

    /**
     * Get the lastActionDateTime property: A timestamp for when the current state was entered.
     * 
     * @return the lastActionDateTime value.
     */
    @Generated
    public String getLastActionDateTime() {
        return this.lastActionDateTime;
    }

    /**
     * Get the status property: Operation status.
     * 
     * @return the status value.
     */
    @Generated
    public OperationStatus getStatus() {
        return this.status;
    }

    /**
     * Get the deviceStatus property: Status of the devices in the operation.
     * 
     * @return the deviceStatus value.
     */
    @Generated
    public List<LogCollectionOperationDeviceStatus> getDeviceStatus() {
        return this.deviceStatus;
    }

    /**
     * Get the description property: Device diagnostics operation description.
     * 
     * @return the description value.
     */
    @Generated
    public String getDescription() {
        return this.description;
    }
}
