// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.iot.deviceupdate.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Installation instruction step that installs another update.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type")
@JsonTypeName("Reference")
@Immutable
public final class ReferenceStep extends Step {
    /*
     * Referenced child update identity.
     */
    @Generated
    @JsonProperty(value = "updateId")
    private UpdateId updateId;

    /**
     * Creates an instance of ReferenceStep class.
     * 
     * @param updateId the updateId value to set.
     */
    @Generated
    @JsonCreator
    private ReferenceStep(@JsonProperty(value = "updateId") UpdateId updateId) {
        this.updateId = updateId;
    }

    /**
     * Get the updateId property: Referenced child update identity.
     * 
     * @return the updateId value.
     */
    @Generated
    public UpdateId getUpdateId() {
        return this.updateId;
    }
}
