// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.iot.deviceupdate.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * The step result under an update.
 */
@Immutable
public final class StepResult {
    /*
     * The update that this step installs if it is of reference type.
     */
    @Generated
    @JsonProperty(value = "update")
    private UpdateInfo update;

    /*
     * Step description.
     */
    @Generated
    @JsonProperty(value = "description")
    private String description;

    /*
     * Install result code.
     */
    @Generated
    @JsonProperty(value = "resultCode")
    private int resultCode;

    /*
     * Install extended result code
     */
    @Generated
    @JsonProperty(value = "extendedResultCode")
    private int extendedResultCode;

    /*
     * A string containing further details about the install result
     */
    @Generated
    @JsonProperty(value = "resultDetails")
    private String resultDetails;

    /**
     * Creates an instance of StepResult class.
     * 
     * @param resultCode the resultCode value to set.
     * @param extendedResultCode the extendedResultCode value to set.
     */
    @Generated
    @JsonCreator
    private StepResult(@JsonProperty(value = "resultCode") int resultCode,
        @JsonProperty(value = "extendedResultCode") int extendedResultCode) {
        this.resultCode = resultCode;
        this.extendedResultCode = extendedResultCode;
    }

    /**
     * Get the update property: The update that this step installs if it is of reference type.
     * 
     * @return the update value.
     */
    @Generated
    public UpdateInfo getUpdate() {
        return this.update;
    }

    /**
     * Get the description property: Step description.
     * 
     * @return the description value.
     */
    @Generated
    public String getDescription() {
        return this.description;
    }

    /**
     * Get the resultCode property: Install result code.
     * 
     * @return the resultCode value.
     */
    @Generated
    public int getResultCode() {
        return this.resultCode;
    }

    /**
     * Get the extendedResultCode property: Install extended result code.
     * 
     * @return the extendedResultCode value.
     */
    @Generated
    public int getExtendedResultCode() {
        return this.extendedResultCode;
    }

    /**
     * Get the resultDetails property: A string containing further details about the install result.
     * 
     * @return the resultDetails value.
     */
    @Generated
    public String getResultDetails() {
        return this.resultDetails;
    }
}
