// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.iot.deviceupdate.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Update install instruction step.
 */
@JsonTypeInfo(
    use = JsonTypeInfo.Id.NAME,
    include = JsonTypeInfo.As.PROPERTY,
    property = "type",
    defaultImpl = Step.class)
@JsonTypeName("Step")
@JsonSubTypes({
    @JsonSubTypes.Type(name = "Inline", value = InlineStep.class),
    @JsonSubTypes.Type(name = "Reference", value = ReferenceStep.class) })
@Immutable
public class Step {
    /*
     * Step description.
     */
    @Generated
    @JsonProperty(value = "description")
    private String description;

    /**
     * Creates an instance of Step class.
     */
    @Generated
    protected Step() {
    }

    /**
     * Get the description property: Step description.
     * 
     * @return the description value.
     */
    @Generated
    public String getDescription() {
        return this.description;
    }
}
