// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.iot.deviceupdate.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Update information.
 */
@Immutable
public final class UpdateInfo {
    /*
     * Update identifier.
     */
    @Generated
    @JsonProperty(value = "updateId", access = JsonProperty.Access.WRITE_ONLY)
    private UpdateId updateId;

    /*
     * Update description.
     */
    @Generated
    @JsonProperty(value = "description", access = JsonProperty.Access.WRITE_ONLY)
    private String description;

    /*
     * Friendly update name.
     */
    @Generated
    @JsonProperty(value = "friendlyName", access = JsonProperty.Access.WRITE_ONLY)
    private String friendlyName;

    /**
     * Creates an instance of UpdateInfo class.
     */
    @Generated
    public UpdateInfo() {
    }

    /**
     * Get the updateId property: Update identifier.
     * 
     * @return the updateId value.
     */
    @Generated
    public UpdateId getUpdateId() {
        return this.updateId;
    }

    /**
     * Get the description property: Update description.
     * 
     * @return the description value.
     */
    @Generated
    public String getDescription() {
        return this.description;
    }

    /**
     * Get the friendlyName property: Friendly update name.
     * 
     * @return the friendlyName value.
     */
    @Generated
    public String getFriendlyName() {
        return this.friendlyName;
    }
}
