// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.iot.deviceupdate.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Update compliance information.
 */
@Immutable
public final class UpdateCompliance {
    /*
     * Total number of devices.
     */
    @Generated
    @JsonProperty(value = "totalDeviceCount")
    private int totalDeviceCount;

    /*
     * Number of devices on the latest update.
     */
    @Generated
    @JsonProperty(value = "onLatestUpdateDeviceCount")
    private int onLatestUpdateDeviceCount;

    /*
     * Number of devices with a newer update available.
     */
    @Generated
    @JsonProperty(value = "newUpdatesAvailableDeviceCount")
    private int newUpdatesAvailableDeviceCount;

    /*
     * Number of devices with update in-progress.
     */
    @Generated
    @JsonProperty(value = "updatesInProgressDeviceCount")
    private int updatesInProgressDeviceCount;

    /**
     * Creates an instance of UpdateCompliance class.
     * 
     * @param totalDeviceCount the totalDeviceCount value to set.
     * @param onLatestUpdateDeviceCount the onLatestUpdateDeviceCount value to set.
     * @param newUpdatesAvailableDeviceCount the newUpdatesAvailableDeviceCount value to set.
     * @param updatesInProgressDeviceCount the updatesInProgressDeviceCount value to set.
     */
    @Generated
    @JsonCreator
    private UpdateCompliance(@JsonProperty(value = "totalDeviceCount") int totalDeviceCount,
        @JsonProperty(value = "onLatestUpdateDeviceCount") int onLatestUpdateDeviceCount,
        @JsonProperty(value = "newUpdatesAvailableDeviceCount") int newUpdatesAvailableDeviceCount,
        @JsonProperty(value = "updatesInProgressDeviceCount") int updatesInProgressDeviceCount) {
        this.totalDeviceCount = totalDeviceCount;
        this.onLatestUpdateDeviceCount = onLatestUpdateDeviceCount;
        this.newUpdatesAvailableDeviceCount = newUpdatesAvailableDeviceCount;
        this.updatesInProgressDeviceCount = updatesInProgressDeviceCount;
    }

    /**
     * Get the totalDeviceCount property: Total number of devices.
     * 
     * @return the totalDeviceCount value.
     */
    @Generated
    public int getTotalDeviceCount() {
        return this.totalDeviceCount;
    }

    /**
     * Get the onLatestUpdateDeviceCount property: Number of devices on the latest update.
     * 
     * @return the onLatestUpdateDeviceCount value.
     */
    @Generated
    public int getOnLatestUpdateDeviceCount() {
        return this.onLatestUpdateDeviceCount;
    }

    /**
     * Get the newUpdatesAvailableDeviceCount property: Number of devices with a newer update available.
     * 
     * @return the newUpdatesAvailableDeviceCount value.
     */
    @Generated
    public int getNewUpdatesAvailableDeviceCount() {
        return this.newUpdatesAvailableDeviceCount;
    }

    /**
     * Get the updatesInProgressDeviceCount property: Number of devices with update in-progress.
     * 
     * @return the updatesInProgressDeviceCount value.
     */
    @Generated
    public int getUpdatesInProgressDeviceCount() {
        return this.updatesInProgressDeviceCount;
    }
}
