// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.iot.deviceupdate.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Update identifier.
 */
@Immutable
public final class UpdateId {
    /*
     * Update provider.
     */
    @Generated
    @JsonProperty(value = "provider")
    private String provider;

    /*
     * Update name.
     */
    @Generated
    @JsonProperty(value = "name")
    private String name;

    /*
     * Update version.Two to four part dot separated numerical version numbers.
     * Each part must be a number between 0 and 2147483647 and leading zeroes will be dropped.
     */
    @Generated
    @JsonProperty(value = "version")
    private String version;

    /**
     * Creates an instance of UpdateId class.
     * 
     * @param provider the provider value to set.
     * @param name the name value to set.
     * @param version the version value to set.
     */
    @Generated
    @JsonCreator
    private UpdateId(@JsonProperty(value = "provider") String provider, @JsonProperty(value = "name") String name,
        @JsonProperty(value = "version") String version) {
        this.provider = provider;
        this.name = name;
        this.version = version;
    }

    /**
     * Get the provider property: Update provider.
     * 
     * @return the provider value.
     */
    @Generated
    public String getProvider() {
        return this.provider;
    }

    /**
     * Get the name property: Update name.
     * 
     * @return the name value.
     */
    @Generated
    public String getName() {
        return this.name;
    }

    /**
     * Get the version property: Update version.Two to four part dot separated numerical version numbers.
     * Each part must be a number between 0 and 2147483647 and leading zeroes will be dropped.
     * 
     * @return the version value.
     */
    @Generated
    public String getVersion() {
        return this.version;
    }
}
