// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.iot.deviceupdate.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.Map;

/**
 * Update metadata.
 */
@Immutable
public final class Update {
    /*
     * Update identity.
     */
    @Generated
    @JsonProperty(value = "updateId", access = JsonProperty.Access.WRITE_ONLY)
    private UpdateId updateId;

    /*
     * Update description specified by creator.
     */
    @Generated
    @JsonProperty(value = "description")
    private String description;

    /*
     * Friendly update name specified by importer.
     */
    @Generated
    @JsonProperty(value = "friendlyName")
    private String friendlyName;

    /*
     * Whether the update can be deployed to a device on its own.
     */
    @Generated
    @JsonProperty(value = "isDeployable")
    private Boolean isDeployable;

    /*
     * Update type. Deprecated in latest import manifest schema.
     */
    @Generated
    @JsonProperty(value = "updateType")
    private String updateType;

    /*
     * String interpreted by Device Update client to determine if the update is
     * installed on the device. Deprecated in latest import manifest schema.
     */
    @Generated
    @JsonProperty(value = "installedCriteria")
    private String installedCriteria;

    /*
     * List of update compatibility information.
     */
    @Generated
    @JsonProperty(value = "compatibility")
    private List<Map<String, String>> compatibility;

    /*
     * Update install instructions.
     */
    @Generated
    @JsonProperty(value = "instructions")
    private Instructions instructions;

    /*
     * List of update identities that reference this update.
     */
    @Generated
    @JsonProperty(value = "referencedBy")
    private List<UpdateId> referencedBy;

    /*
     * Update aggregate scan result (calculated from payload file scan results).
     */
    @Generated
    @JsonProperty(value = "scanResult")
    private String scanResult;

    /*
     * Schema version of manifest used to import the update.
     */
    @Generated
    @JsonProperty(value = "manifestVersion")
    private String manifestVersion;

    /*
     * Date and time in UTC when the update was imported.
     */
    @Generated
    @JsonProperty(value = "importedDateTime")
    private OffsetDateTime importedDateTime;

    /*
     * Date and time in UTC when the update was created.
     */
    @Generated
    @JsonProperty(value = "createdDateTime")
    private OffsetDateTime createdDateTime;

    /*
     * Update ETag.
     */
    @Generated
    @JsonProperty(value = "etag")
    private String etag;

    /**
     * Creates an instance of Update class.
     * 
     * @param compatibility the compatibility value to set.
     * @param manifestVersion the manifestVersion value to set.
     * @param importedDateTime the importedDateTime value to set.
     * @param createdDateTime the createdDateTime value to set.
     */
    @Generated
    @JsonCreator
    private Update(@JsonProperty(value = "compatibility") List<Map<String, String>> compatibility,
        @JsonProperty(value = "manifestVersion") String manifestVersion,
        @JsonProperty(value = "importedDateTime") OffsetDateTime importedDateTime,
        @JsonProperty(value = "createdDateTime") OffsetDateTime createdDateTime) {
        this.compatibility = compatibility;
        this.manifestVersion = manifestVersion;
        this.importedDateTime = importedDateTime;
        this.createdDateTime = createdDateTime;
    }

    /**
     * Get the updateId property: Update identity.
     * 
     * @return the updateId value.
     */
    @Generated
    public UpdateId getUpdateId() {
        return this.updateId;
    }

    /**
     * Get the description property: Update description specified by creator.
     * 
     * @return the description value.
     */
    @Generated
    public String getDescription() {
        return this.description;
    }

    /**
     * Get the friendlyName property: Friendly update name specified by importer.
     * 
     * @return the friendlyName value.
     */
    @Generated
    public String getFriendlyName() {
        return this.friendlyName;
    }

    /**
     * Get the isDeployable property: Whether the update can be deployed to a device on its own.
     * 
     * @return the isDeployable value.
     */
    @Generated
    public Boolean isDeployable() {
        return this.isDeployable;
    }

    /**
     * Get the updateType property: Update type. Deprecated in latest import manifest schema.
     * 
     * @return the updateType value.
     */
    @Generated
    public String getUpdateType() {
        return this.updateType;
    }

    /**
     * Get the installedCriteria property: String interpreted by Device Update client to determine if the update is
     * installed on the device. Deprecated in latest import manifest schema.
     * 
     * @return the installedCriteria value.
     */
    @Generated
    public String getInstalledCriteria() {
        return this.installedCriteria;
    }

    /**
     * Get the compatibility property: List of update compatibility information.
     * 
     * @return the compatibility value.
     */
    @Generated
    public List<Map<String, String>> getCompatibility() {
        return this.compatibility;
    }

    /**
     * Get the instructions property: Update install instructions.
     * 
     * @return the instructions value.
     */
    @Generated
    public Instructions getInstructions() {
        return this.instructions;
    }

    /**
     * Get the referencedBy property: List of update identities that reference this update.
     * 
     * @return the referencedBy value.
     */
    @Generated
    public List<UpdateId> getReferencedBy() {
        return this.referencedBy;
    }

    /**
     * Get the scanResult property: Update aggregate scan result (calculated from payload file scan results).
     * 
     * @return the scanResult value.
     */
    @Generated
    public String getScanResult() {
        return this.scanResult;
    }

    /**
     * Get the manifestVersion property: Schema version of manifest used to import the update.
     * 
     * @return the manifestVersion value.
     */
    @Generated
    public String getManifestVersion() {
        return this.manifestVersion;
    }

    /**
     * Get the importedDateTime property: Date and time in UTC when the update was imported.
     * 
     * @return the importedDateTime value.
     */
    @Generated
    public OffsetDateTime getImportedDateTime() {
        return this.importedDateTime;
    }

    /**
     * Get the createdDateTime property: Date and time in UTC when the update was created.
     * 
     * @return the createdDateTime value.
     */
    @Generated
    public OffsetDateTime getCreatedDateTime() {
        return this.createdDateTime;
    }

    /**
     * Get the etag property: Update ETag.
     * 
     * @return the etag value.
     */
    @Generated
    public String getEtag() {
        return this.etag;
    }
}
