// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.iot.deviceupdate.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Download handler for utilizing related files to download payload file.
 */
@Immutable
public final class UpdateFileDownloadHandler {
    /*
     * Download handler identifier.
     */
    @Generated
    @JsonProperty(value = "id")
    private String id;

    /**
     * Creates an instance of UpdateFileDownloadHandler class.
     * 
     * @param id the id value to set.
     */
    @Generated
    @JsonCreator
    private UpdateFileDownloadHandler(@JsonProperty(value = "id") String id) {
        this.id = id;
    }

    /**
     * Get the id property: Download handler identifier.
     * 
     * @return the id value.
     */
    @Generated
    public String getId() {
        return this.id;
    }
}
