// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) TypeSpec Code Generator.

package com.azure.iot.deviceupdate.models;

import com.azure.core.annotation.Generated;
import com.azure.core.annotation.Immutable;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A counter with both usage and quota information.
 */
@Immutable
public final class UsageQuotaCounter {
    /*
     * The current number of the resource that exist
     */
    @Generated
    @JsonProperty(value = "usage")
    private int usage;

    /*
     * The maximum number of the resource that can be created
     */
    @Generated
    @JsonProperty(value = "quota")
    private int quota;

    /**
     * Creates an instance of UsageQuotaCounter class.
     * 
     * @param usage the usage value to set.
     * @param quota the quota value to set.
     */
    @Generated
    @JsonCreator
    private UsageQuotaCounter(@JsonProperty(value = "usage") int usage, @JsonProperty(value = "quota") int quota) {
        this.usage = usage;
        this.quota = quota;
    }

    /**
     * Get the usage property: The current number of the resource that exist.
     * 
     * @return the usage value.
     */
    @Generated
    public int getUsage() {
        return this.usage;
    }

    /**
     * Get the quota property: The maximum number of the resource that can be created.
     * 
     * @return the quota value.
     */
    @Generated
    public int getQuota() {
        return this.quota;
    }
}
